sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kssidhu/docker-react-study -f Dockerfile.dev .

script:
  - docker run -e CI=true kssidhu/docker-react-study npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-study"
  env: "Dockerstudy-env"
  bucket_name: "elasticbeanstalk-us-east-2-770403209712"
  bucket_path: "docker-study"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
